---
- name: Health-check Test
  hosts: all
  connection: local
  vars:
      - target_ip: "{{ansible_ssh_host}}"
      - port: "{{ansible_ssh_port}}"
  collections:
  - piolink.pask

  tasks:

  - name: Create health-check
    pask_health_check:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "500"
      type: "tcp"
      half_open: "enable"
      increase_icmp_id: "enable"
      interval: "53"
      mac: "00:06:c4:94:02:27"
      port: "5004"
      retry: "2"
      timeout: "4"

  - name: Delete health-check
    pask_health_check:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "500"
      state: "absent"
