---
- name: Self Test Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Command Self Test(same core)
    pask_self_test:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"

  - name: Command Self Test(all)
    pask_self_test:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      all: "all"

  - name: Command Self Test(core)
    pask_self_test:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      core: "core"

  - name: Command Self Test(pcilink)
    pask_self_test:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      pcilink: "pcilink"