---
- name: Prescript Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Prescript
    pask_prescript:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test"
      import_url: "ftp://tester:test123@1.1.1.1/test.lua"
      description: "test"

  - name: Delete Prescript
    pask_prescript:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test"
      state: "absent"
