---
- name: Log Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Delete Log history
    pask_log:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      state: "absent"

  - name: Delete Log history All
    pask_log:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      all: "yes"
      state: "absent"