---
- name: Terminal Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Terminal
    pask_terminal:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      timeout: "30"
      length: "50"

  - name: Reset Terminal
    pask_terminal:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"