---
- name: Persist L7 Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Delete Persist L7 All
    pask_persist_l7:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      state: "absent"