---
- name: Resource Management Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Resource Management
    pask_resource_management:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      mp: {cpus: "5", memory: "2048"}

  - name: Reset Resource Management
    pask_resource_management:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"