---
- name: create real
  connection: local
  hosts: targets
  collections:
  - piolink.pask

  tasks:
  - name: Create real
    pask_real:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "101"
      rip: "172.16.123.24"
      rport: "5544"
      priority: "30"
      weight: "50"
      graceful_shutdown: "enable"
      max_connection: "12"
      upload_bandwidth: "100000"
      download_bandwidth: "200000"
      domain_filter: "1"
      pool_size: "100"
      pool_age: "200"
      pool_reuse: "300"
      pool_srcmask: "14"
      src_natip: "5.4.3.2"
      status: "disable"
      state: "present"

  - name: Delete real
    pask_real:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "101"
      rip: "172.16.123.24"
      state: "absent"
