---
- name: Vlan Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Vlan
    pask_vlan:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test_vlan"
      vid: "3200"
      port:
        - name: "ge1"
          type: "tagged"
      tbm: "enable"
      description: "test"

  - name: Delete Vlan
    pask_vlan:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test_vlan"
      state: "absent"