---
- name: Router6 Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Router6
    pask_router6:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      advertisement_status: "enable"

  - name: Reset Router6
    pask_router6:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"