---
- name: Warranty License Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Warranty License
    pask_warranty_license:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      warranty_license:
        - license: "XXXXXX"
          lvc: "XXXXXX"