---
- name: Lsn Nat64 Prefix Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Lsn Nat64 Prefix
    pask_lsn_nat64_prefix:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "1"
      network: "2002:22::/64"

  - name: Delete Lsn Nat64 Prefix
    pask_lsn_nat64_prefix:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "1"
      state: "absent"