---
- name: Entry Nat64 Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Delete Entry Nat64 All
    pask_entry_nat64:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      state: "absent"