---
- name: Entry Detail Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Delete Entry Detail(dport)
    pask_entry_detail:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      dport:
        - dport: "80"
      state: "absent"

  - name: Delete Entry Detail(service&name)
    pask_entry_detail:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      service:
        - service: "advl7slb"
          name: "s1"
      state: "absent"

  - name: Delete Entry Detail All
    pask_entry_detail:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      state: "absent"