---
- name: Domain Filter Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Domain Filter
    pask_domain_filter:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "1"
      domain: "google"
      description: "test"

  - name: Delete Domain Filter
    pask_domain_filter:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "1"
      state: "absent"