---
- name: Route Module Test
  connection: local
  hosts: targets
  collections:
  - piolink.pask

  tasks:
  - name: Set route
    pask_route:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      network:
        - dest: "10.10.0.0/16"
          gateway:
            - gateway: "10.10.10.1"
              priority: "20"
              health_check:
                - id: "1"
          description: "test1"
        - dest: "10.20.0.0/16"
          interface:
            - interface: "v2933"
              interface: "v2944"
          description: "test2"
      default_gateway:
        - gateway: "192.168.214.1"
          health_check:
            - id: "1"
          priority: "100"

  - name: Reset route
    pask_route:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      default_gateway:
        - gateway: "192.168.214.1"