---
- name: License Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set License
    pask_license:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      license: "XXXXXX"