---
- name: Entry Adv Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Delete Entry Adv All
    pask_entry_adv:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      state: "absent"