---
- name: Fan Hotswap Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Fan Hotswap
    pask_fan_hotswap:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      status: "enable"

  - name: Reset Fan Hotswap
    pask_fan_hotswap:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"