---
- name: Dhcp Relay Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Dhcp Relay
    pask_dhcp_relay:
      prest_ip: "{{ansible_host}}"
      prest_port: "{{ansible_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      ip:
        - { serverip : "1.1.1.1" }
      interface:
        - { name : "lan" }
      option: "append"
      status: "enable"

  - name: Reset Dhcp Relay
    pask_dhcp_relay:
      prest_ip: "{{ansible_host}}"
      prest_port: "{{ansible_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"