---
- name: Date Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Date
    pask_date:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      date: "03/25/2024 12:30:45"