---
- name: Vinstance Os Update Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Command Vinstance Os Update
    pask_vinstance_os_update:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      profile: "test mgmt active"