---
- name: Hostname Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Hostname
    pask_hostname:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      hostname: "switch_ansible"

  - name: Reset Hostname
    pask_hostname:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      state: "absent"
