---
- name: Nat Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Nat
    pask_nat:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      status: "enable"
      filter:
        - id: "1"
          priority: "1"
          type: "dest-nat"
          status: "enable"
          protocol: "icmp"
          sip: "1.1.1.1/24"
          dip: "10.10.10.10/24"
          dnatip:
            - "1.1.1.1"
          description: "test"

  - name: Reset Nat
    pask_nat:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"