---
- name: Pvstp Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Pvstp Pre-Processing(Vlan Port Set)
    pask_pvstp:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      status: "enable"
      mode: "pvst-plus"
      bridge_forward_delay: "20"
      bridge_hello_time: "3"
      bridge_max_age: "10"
      priority: "10"
      bpdu_guard: "enable"
      port:
        - name: "ge1"
          priority: "10"
          path_cost: "200"
          portfast: "enable"
          bpdu_guard: "enable"
          bpdu_filter: "enable"
          root_guard: "enable"
        - name: "ge2"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge3"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge4"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge5"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge6"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge7"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge8"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg1"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg2"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg3"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg4"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg5"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg6"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg7"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg8"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg9"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg10"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg11"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg12"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg13"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg14"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg15"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg16"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
      vlan:
        - vlan_name: "test_vlan"
          instance: "3"
          bridge_forward_delay: "20"
          bridge_hello_time: "3"
          bridge_max_age: "10"
          priority: "10"

  - name: Set Pvstp Vlan Port Set
    pask_pvstp:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      status: "enable"
      mode: "pvst-plus"
      bridge_forward_delay: "20"
      bridge_hello_time: "3"
      bridge_max_age: "10"
      priority: "10"
      bpdu_guard: "enable"
      port:
        - name: "ge1"
          priority: "10"
          path_cost: "200"
          portfast: "enable"
          bpdu_guard: "enable"
          bpdu_filter: "enable"
          root_guard: "enable"
        - name: "ge2"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge3"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge4"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge5"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge6"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge7"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "ge8"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg1"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg2"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg3"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg4"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg5"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg6"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg7"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg8"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg9"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg10"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg11"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg12"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg13"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg14"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg15"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
        - name: "xg16"
          priority: "8"
          portfast: "disable"
          bpdu_guard: "disable"
          bpdu_filter: "disable"
          root_guard: "disable"
      vlan:
        - vlan_name: "test_vlan"
          instance: "3"
          bridge_forward_delay: "20"
          bridge_hello_time: "3"
          bridge_max_age: "10"
          priority: "10"
          port:
            - name: "ge1"
              priority: "10"
              path_cost: "300"

  - name: Reset Pvstp
    pask_pvstp:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      port:
        - name: "ge1"
        - name: "ge2"
        - name: "ge3"
        - name: "ge4"
        - name: "ge5"
        - name: "ge6"
        - name: "ge7"
        - name: "ge8"
        - name: "xg1"
        - name: "xg2"
        - name: "xg3"
        - name: "xg4"
        - name: "xg5"
        - name: "xg6"
        - name: "xg7"
        - name: "xg8"
        - name: "xg9"
        - name: "xg10"
        - name: "xg11"
        - name: "xg12"
        - name: "xg13"
        - name: "xg14"
        - name: "xg15"
        - name: "xg16"