---
- name: Site Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Site
    pask_site:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test"
      location: "local"
      retry: 5
      synchronize: "enable"
      peer:
        - id: 2
          ip: "1.1.1.1"
          description: "site peer"
      interval: "60"
      status: "enable"
      description: "test1"

  - name: Delete Site
    pask_site:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test"
      state: "absent"