---
- name: Dual Boot Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Dual Boot
    pask_dual_boot:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      next_boot_image: "previous"

  - name: Reset Dual Boot
    pask_dual_boot:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"

