---
- name: System Check Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Command System Check
    pask_system_check:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      type: "integrity"