---
- name: Banner Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Banner
    pask_banner:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      login: "test"
      motd: "test"

  - name: Reset Banner
    pask_banner:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"