---
- name: Shutdown Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Command Shutdown
    pask_shutdown:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      verify: "yes"