---
- name: User Session Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Delete User Session
    pask_user_session:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "27738"
      state: "absent"