---
- name: Failover Test
  hosts: all
  connection: local
  collections:
    - piolink.pask
  tasks:
    - name: Set Failover(ha)
      pask_failover:
        prest_ip: "{{ansible_host}}"
        prest_port: "{{ansible_port}}"
        user_id: "{{user_id}}"
        user_pw: "{{user_pw}}"
        delay_time: "20"
        active_active_failover:
          method: "bdr"
          vlan: "lan"
          health_check:
            - id: "256"
            - id: "512"
        vrrp:
          - id: "1"
            status: "disable"
            priority: "50"
            svip:     # svip and send-garp-all-svip enable must not be configured at the same time.
              - "4.4.4.4"
              - "5.5.5.5"
            send_garp_all_svip: "disable"      # svip and send-garp-all-svip enable must not be configured at the same time.
            mode: "active-active"
            port_boundary:
              - "1"
              - "2"
            port_block:
              - "ge4"
              - "ge5"
            interface:
              - name: "v3200"
                advertise_send: "enable"
                vip:
                  - "2.2.2.2"
                  - "3.3.3.3"
                overlapped: "on"
              - name: "v3600"
                advertise_send: "disable"
                vip:
                  - "10.10.10.10"
                  - "11.11.11.11"
            track:
              member_port:
                - id: "1"
                  port:
                    - "ge1"
                    - "ge2"
                  priority: "15"
              single_port:
                - priority: "3"
                  port:
                    - "ge6"
                    - "ge3"
                - priority: "5"
                  port:
                    - "ge1"
                    - "ge4"
              real:
                - id: "1"
                  priority: "5"
                - id: "2"
                  priority: "10"
            advertise_interval: "30"
            retry: "5"
            arp_count: "5"
            vmac: "disable"
            preemption: "disable"
            description: "test3"
        vrrp6:
          - id: "1"
            status: "disable"
            priority: "50"
            svip:
                - 3001:0db8:85a3:0000:0000:8a3e:0371:ec14
                - 3001:0db8:85a3:0000:0000:8a4e:0371:ec14
            mode: "active-active"
            port_boundary:
              - "1"
              - "2"
            port_block:
              - "ge4"
              - "ge5"
            interface:
              - name: "v3200"
                advertise_send: "disable"
                vllip: "2001:0db8:85a3:0000:0000:8a2e:0371:ec14"
                vip:
                  - "2001:0db8:85a3:0000:0000:8a3e:0371:ec14"
                  - "2001:0db8:85a3:0000:0000:8a4e:0371:ec14"
            track:
              member_port:
                - id: "1"
                  port:
                    - "ge1"
                    - "ge2"
                  priority: "15"
              single_port:
                - priority: "3"
                  port:
                    - "ge6"
                    - "ge3"
                - priority: "5"
                  port:
                    - "ge1"
                    - "ge4"
              real:
                - id: "1"
                  priority: "5"
                - id: "2"
                  priority: "10"
            advertise_interval: "30"
            retry: "5"
            mc_retry: "1"
            vmac: "disable"
            preemption: "disable"
            description: "test3"
        ha:
          status: "enable"
          svip:
            - "6.6.6.6"
            - "7.7.7.7"
          interface:
            - name: "lon"
              heartbeat_send: "enable"
              vip:
                - "8.8.8.8"
                - "9.9.9.9"
          node:
            - name: "test4"
              ip: "1.1.1.10"
              description: "test7"
          heartbeat_interval: "20"
          retry: "5"
          vmac: "disable"
        ssl_session_cache_sync:
          status: "enable"
          interface:
            name: "test_vlan"
            ip: "1.1.1.1/24"
            peer_ip: "1.1.1.10"

    - name: Set Failover(session_sync)
      pask_failover:
        prest_ip: "{{ansible_host}}"
        prest_port: "{{ansible_port}}"
        user_id: "{{user_id}}"
        user_pw: "{{user_pw}}"
        session_sync:
          status: "enable"
          interval: "50"
          full_interval: "50"
          update: "full"
          peer: "node1"
          interface:
            name: "lan"
            ip: "1.1.1.2/24"
            peer_ip: "1.1.1.3"
            hc_retry: "4"
        ha:
          status: "disable"
          node:
            - name: "test4"
              ip: "1.1.1.10"
              description: "test7"
          default_state: "backup"
        ssl_session_cache_sync:
          status: "enable"
          interface:
            name: "test_vlan"
            ip: "1.1.1.1/24"
            peer_ip: "1.1.1.10"

    - name: Reset Failover
      pask_failover:
        prest_ip: "{{ansible_host}}"
        prest_port: "{{ansible_port}}"
        user_id: "{{user_id}}"
        user_pw: "{{user_pw}}"