---
- name: Rdate Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Command Rdate
    pask_rdate:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      host: "1.1.1.1"