---
- name: Access User Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Access User
    pask_access_user:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      status: "enable"
      max_user: "3"

  - name: Reset Access User
    pask_access_user:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"