---
- name: Watch System Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Watch System
    pask_watch_system:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      cpu: {threshold: "100"}
      memory: {threshold: "100"}
      log_storage: {threshold: "100"}

  - name: Reset Watch System
    pask_watch_system:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"