---
- name: Timezone Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Timezone
    pask_timezone:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      timezone: "UTC-03:00"

  - name: Reset Timezone
    pask_timezone:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"