---
- name: Arp-Filter Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: set arp-filter
    pask_arp_filter:
      prest_ip: "{{ansible_host}}"
      prest_port: "{{ansible_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      input:
        - {id: "1", action: "accept", sip: "1.1.1.1/24", dip: "2.1.1.1/24", description: "Description of the input arp filter", interface: "test" }
      output:
        - {id: "2", action: "drop", sip: "2.1.1.1/24", dip: "1.1.1.1/24", description: "Description of the output arp filter", interface: "test" }

  - name: reset arp-filter
    pask_arp_filter:
      prest_ip: "{{ansible_host}}"
      prest_port: "{{ansible_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"