---
- name: Sp Filter Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Create Sp Filter
    pask_sp_filter:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "1"
      ip: "1.1.1.1/24"
      description: "test"

  - name: Delete Sp Filter
    pask_sp_filter:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      id: "1"
      state: "absent"