---
- name: Interface Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Modify Interface
    pask_interface:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test"
      status: "up"
      adv_send_advert: "disable"
      adv_default_lifetime: "3600"
      min_rtr_adv_interval: "200"
      max_rtr_adv_interval: "800"
      adv_cur_hop_limit: "100"
      adv_reachable_time: "300"
      adv_retrans_timer: "300"
      mtu: "2000"
      arp_ignore: "3"
      arp_announce: "1"
      description: "test"
      rpf: "strict"
      ip:
        - address: "1.1.1.1/24"
          broadcast: "1.1.1.255"
          overlapped: "on"
      ip6:
        - address: "2001:0db8:85a3:0000:0000:8a2e:0370:7334/64"
          broadcast: "2001:db8:85a3:0:ffff:ffff:ffff:ffff"
          adv_on_link: "disable"
          adv_autonomous: "disable"
          adv_router_addr: "enable"
          adv_valid_lifetime: "30000000"
          adv_preferred_lifetime: "1000000"

  - name: Reset Interface
    pask_interface:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      name: "test"