---
- name: Dom Test
  hosts: all
  connection: local
  collections:
  - piolink.pask

  tasks:
  - name: Set Dom
    pask_dom:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      interval: "500"
      status: "enable"

  - name: Reset Dom
    pask_dom:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"